export const IpcChannel = {
  Bootstrap: 'app:bootstrap',

  DocumentsList: 'documents:list',
  DocumentsSearch: 'documents:search',
  DocumentsGet: 'documents:get',
  DocumentsUpdate: 'documents:update',
  DocumentsSetStarred: 'documents:setStarred',
  DocumentsDelete: 'documents:delete',
  DocumentsBulkDelete: 'documents:bulkDelete',
  DocumentsBulkCategorize: 'documents:bulkCategorize',
  DocumentsBulkRefreshMetadata: 'documents:bulkRefreshMetadata',
  DocumentsCountPendingMetadata: 'documents:countPendingMetadata',
  DocumentsOpenPdf: 'documents:openPdf',
  DocumentsOpenInFinder: 'documents:openInFinder',
  DocumentsRefreshMetadata: 'documents:refreshMetadata',
  DocumentsRelocateFile: 'documents:relocateFile',
  DocumentsRestoreFile: 'documents:restoreFile',

  ImportAddFiles: 'import:addFiles',
  ImportAddFolder: 'import:addFolder',
  ImportFromJson: 'import:fromJson',

  CategoriesList: 'categories:list',
  CategoriesCreate: 'categories:create',
  CategoriesRename: 'categories:rename',
  CategoriesDelete: 'categories:delete',
  CategoriesAssign: 'categories:assign',
  CategoriesUnassign: 'categories:unassign',

  WatchList: 'watch:list',
  WatchAdd: 'watch:add',
  WatchRemove: 'watch:remove',
  WatchToggle: 'watch:toggle',

  DialogOpenDirectory: 'dialog:openDirectory',

  LibrarySwitch: 'library:switch',

  SettingsGet: 'settings:get',
  SettingsSet: 'settings:set',

  ExportToJson: 'export:toJson',
  ExportToBibtex: 'export:toBibtex',
  ExportBibtexString: 'export:bibtexString',

  WorkspacesList: 'workspaces:list',
  WorkspacesCreate: 'workspaces:create',
  WorkspacesRename: 'workspaces:rename',
  WorkspacesDelete: 'workspaces:delete',

  WorkspaceItemsList: 'workspaceItems:list',
  WorkspaceItemsAdd: 'workspaceItems:add',
  WorkspaceItemsRemove: 'workspaceItems:remove',
  WorkspaceItemsReorder: 'workspaceItems:reorder',

  AiProvidersList: 'ai:providers:list',
  AiProvidersCreate: 'ai:providers:create',
  AiProvidersUpdate: 'ai:providers:update',
  AiProvidersDelete: 'ai:providers:delete',
  AiProvidersTest: 'ai:providers:test',
  AiProvidersListModels: 'ai:providers:listModels',

  AiDocTextGet: 'ai:docText:get',
  AiSummarize: 'ai:summarize',
  AiSummaryGet: 'ai:summary:get',

  AiChatSend: 'ai:chat:send',
  AiChatHistory: 'ai:chat:history',
  AiChatThreads: 'ai:chat:threads',
  AiChatTraces: 'ai:chat:traces',
  AiChatCancel: 'ai:chat:cancel',
  AiChatDeleteThread: 'ai:chat:deleteThread',
  AiChatRenameThread: 'ai:chat:renameThread',

  AiReportsList: 'ai:reports:list',
  AiReportsDelete: 'ai:reports:delete',
  AiReportsUpdate: 'ai:reports:update',

  EventDocumentUpdated: 'document:updated',
  EventWindowFocusChanged: 'window:focus-changed',
  EventImportProgress: 'import:progress',
  EventImportToast: 'import:toast',
  EventMenuExportBibtex: 'menu:export-bibtex',
  EventLibraryScanning: 'library:scanning',
  EventLibrarySwitched: 'library:switched',
  EventAiSummaryUpdated: 'ai:summary:updated',
  EventAiSummaryError: 'ai:summary:error',
  EventAiChatToken: 'ai:chat:token',
  EventAiChatReasoning: 'ai:chat:reasoning',
  EventAiChatDone: 'ai:chat:done',
  EventAiChatError: 'ai:chat:error',
  EventAiChatTrace: 'ai:chat:trace',
  EventAiChatTitleUpdated: 'ai:chat:titleUpdated',
  EventAiReportCreated: 'ai:report:created',
  EventWorkspaceItemsChanged: 'workspace:items:changed'
} as const
